### ISSUE TITLE
camera/imagearraybinary URL has extra /

### ISSUE THREAD

**Issue by hollanderic** [ASCOMInitiative/ASCOMRemote#10]
Concating strings to create ([link to line of code](https://github.com/ASCOMInitiative/ASCOMRemote/blob/master/Remote%20Client%20Local%20Server/RemoteClientDriver.cs#L718)) URL results in an extra '/' in the url: example:

http://localhost//api/v1/camera/cooleron
[](url)

**Comment by Peter-Simpson** [comment]
Hi Eric,

As far as I can see this is only an issue in the experimental BinaryFormatter support that I have now removed as described in issue #11 I think I can close this issue given that things have moved on, do you agree?

Regards, Peter

**Comment by hollanderic** [comment]
agreed.  Thanks again for providing good context in #11.
