### ISSUE TITLE
Support for Flat / FlipFlat / Dust cover devices

### ISSUE THREAD

**Issue by linuxkidd** [ASCOMInitiative/ASCOMRemote#12]
Looking over the Alpaca API, I notice there appears not to be any support for flat field or dust cover devices.  Is this planned?

Thanks!

**Comment by Peter-Simpson** [comment]
Regards, Peter

**Comment by Peter-Simpson** [comment]
Hi,

Yes it is, I'm just drafting an RFC to post on the ASCOM Developer forum. Hopefully this should be up in the next 7 days.

Regards, Peter

**Comment by Peter-Simpson** [comment]
I'm closing this issue because the CoverCalibrator interface has been through RFC and is now finalised. It will be implemented in the forthcoming Platform 6.5, which will be released in the next one to two months.
