### ISSUE TITLE
Looking for documentation for CoverCalibrator api endpoints

### ISSUE THREAD

**Issue by linuxkidd** [ASCOMInitiative/ASCOMRemote#16]
Is there documentation for CoverCalibrator api endpoint?   I haven't located it in `ASCOM Alpaca API Reference.pdf` file or the https://ascom-standards.org/api/ site.

Thanks!

**Comment by linuxkidd** [comment]
@Peter-Simpson I don't think your update came through the way you intended... :)

**Comment by Peter-Simpson** [comment]
Hi Michael,

As #15, I really don't know how my empty post came about, sorry!

We haven't finished the online documentation for the CoverCalibrator Alpaca API yet, there isn't an issue of any kind, it will follow the same principles as the other APIs, the timing is just down to workload prioritisation. 

If you examine how similar methods are implemented in other interfaces, I think you will be able to deduce pretty much what the interface will be.

We hope to publish Platform 6.5 (including the Alpaca API spec) next week.

Best wishes, Peter

**Comment by linuxkidd** [comment]
Sounds great Peter, thanks for the update! :)

**Comment by jamessynge** [comment]
This can probably be closed now.

**Comment by Peter-Simpson** [comment]
The API has been published, so I'm closing this issue as suggested.

Best wishes, Peter
