### ISSUE TITLE
Property or Method error

### ISSUE THREAD

**Issue by forna91** [ASCOMInitiative/ASCOMRemote#17]
Hi Peter as We talked in Ascom Developer forum, in documentation is missing the difference fro proprerty or Method not implemented error (using the error message) .
I don't know, but it can be usefull

**Comment by Peter-Simpson** [comment]
Hi,

Thanks, I've revised the code to address this issue and the fix will be in Platform 6.5 Service Pack 1 that will be released shortly.

Best wishes, Peter
