### ISSUE TITLE
Time unit is unspecified for two ObservingConditions methods

### ISSUE THREAD

**Issue by jamessynge** [ASCOMInitiative/ASCOMRemote#26]
GET averageperiod and GET timesincelastupdate don't specify the time unit of the value field in the response. I'm guessing that it is hours based on PUT averageperiod.

**Comment by Peter-Simpson** [comment]
The time units (hours for AveragePeriod and seconds for TimeSinceLastUpdate) are documented in the interface specification here: [ASCOM Interface Definitions](https://ascom-standards.org/Help/Developer/html/T_ASCOM_DeviceInterface_IObservingConditions.htm).

We are currently working on bringing the information in the Alpaca API and the Interface definition documents together.

Regards, Peter
