### ISSUE TITLE
Example path has wrong case

### ISSUE THREAD

**Issue by jamessynge** [ASCOMInitiative/ASCOMRemote#28]
In section 3.8.6, Driver Error Example, of [ASCOM Alpaca API Reference](https://github.com/ASCOMInitiative/ASCOMRemote/blob/master/Documentation/ASCOM%20Alpaca%20API%20Reference.pdf), the example path uses mixed case, instead of lower-case:

`PUT /api/v1/Telescope/0/SiteElevation`

This should read:

`PUT /api/v1/telescope/0/siteelevation`

**Comment by Peter-Simpson** [comment]
Thanks James, I've corrected the documentation and it will appear in the next release.

Best wishes, Peter
