### ISSUE TITLE
Out of Memory while exposing with full frame camera

### ISSUE THREAD

**Issue by mhambuch** [ASCOMInitiative/ASCOMRemote#33]
Hello,

I am connecting my ZWOASI6200 camera over alcapa in mountwizzard4. In that application i expose N for polar alignment. When doing this in full frame bin1 i get a crash.

Marc

[ASCOM.RemoteAccessServerException.1804.506310.txt](https://github.com/ASCOMInitiative/ASCOMRemote/files/7111987/ASCOM.RemoteAccessServerException.1804.506310.txt)

**Comment by Peter-Simpson** [comment]
I'm unable to reproduce this here using the Camera Simulator running in the Remote Server returning a 9600 x 6400 monochrome image. Is this still an issue?

**Comment by Peter-Simpson** [comment]
Closing due to no further activity.
