### ISSUE TITLE
Extra listening IP adres on ascom remote

### ISSUE THREAD

**Issue by calberts** [ASCOMInitiative/ASCOMRemote#34]
Hoi

I have a question although I think it's not a bug but Request for enhancement

I use Alpaca for my remote observatory, I  love it. I use it to open my roof and query my PC for the status of the telescope with ascom remote. That all is on the local network with the observatory. To control and access the observatory I make use of zero-tier (https://www.zerotier.com/). Which introduced an overlay network with another network IP space.
ALPACA Remote Servers is only able to listen on one network one 1 address, 
My enhancement question is to add an extra one listing IP address in Ascom remote for the zerotier network.

This has added value for all remote observatory's 
The reason for me is that I like to use the sky safari from my Mac / iPad at home which has full alpaca support presently added

In this way, we control equipment at home but still also local in the observatory

Looking forward to this enhancement.

With regards 

Chris Alberts

**Comment by Peter-Simpson** [comment]
Hi Chris,

The latest ASCOM remote release [here](https://github.com/ASCOMInitiative/ASCOMRemote/releases) has an "All IP Addresses" option, does this address your need?

Best wishes, Peter

![image](https://user-images.githubusercontent.com/38855929/141296474-42644a13-2d67-4f9e-b9bb-224482c7d7f1.png)

**Comment by calberts** [comment]
Peter

I will check this, I'm still on version 7500 fist update to the last release ;-)

Thanks for you reaction

Chris

**Comment by calberts** [comment]
Peter

this did the Job, thanks ist working

Chris

**Comment by Peter-Simpson** [comment]
Hi Chris,

That's great, I'm glad it's working OK.

Best wishes, Peter
