### ISSUE TITLE
Exception while attempting to start the API discovery listeners

### ISSUE THREAD

**Issue by michealroberts** [ASCOMInitiative/ASCOMRemote#37]
So, I have a Alpaca ASCOM API remote server set up on a VM machine on Azure*, at the port 8010 (***_for testing purposes_**)

However, for some reason, the connection hangs and is unable to respond.

Within the Windows Server VM, if I open any browser, and say navigate to: `http://127.0.0.1:8010/api/v1/telescope/0/altitude` I see the following response:

```
{"Value":38.92139,"ClientTransactionID":0,"ServerTransactionID":11,"ErrorNumber":0,"ErrorMessage":"","DriverException":null}
```

So I can confirm that it seems to be working, and working as intended.

I have also whitelisted inbound connections to 8010 within the VM, using Windows Firewall rules, and I have also added an inbound port rule to the network handling, but there still is the infinite hang.

There is certainly something I have done wrong in configuring the server, perhaps something to do with this:

<img width="246" alt="Screenshot 2022-08-15 at 14 22 18" src="https://user-images.githubusercontent.com/84131395/184643536-e3a02213-7695-4f8b-8ec7-317de4256824.png">

However, when I add the IP address of the public IP address for the VM, I see the following issue:

<img width="557" alt="Screenshot 2022-08-15 at 14 26 05" src="https://user-images.githubusercontent.com/84131395/184643919-c1383ba5-db1a-440e-a50a-e46a789db01a.png">

So, it can't seem to discover ... 

Would anyone be able to work with me to understand how to setup on a VM?

**Comment by michealroberts** [comment]
Ooof, always the way, as soon as you try something it works! Haha

So it seems that if you set it to an IP address you need to stop and the start the server again... D'oh!

**Comment by Peter-Simpson** [comment]
Hi Michael, glad you have it sorted!

Best wishes, Peter
