### ISSUE TITLE
Allow for custom park and home positions

### ISSUE THREAD

**Issue by dyfiastro** [ASCOMInitiative/ASCOMRemote#4]
I am currently trying to get ascom remote working with multiple EQMOD controlled mounts.
These all have custom home positions set to allow for the roof to roll on and off.

Without the ability to select a custom home position to park to using ascom remote I still currently need to log in to the remote PC to set the custom home position.

**Comment by Peter-Simpson** [comment]
Hi,

Are you saying that Telescope.SetPark is not working in ASCOM Remote?

Regards Peter

**Comment by dyfiastro** [comment]
No it seems to park to the standard park position (Scope up, weights down).
However I have separate park positions that can be called to allow the roof to be rolled on and off.
I cannot see a way to call these as a separate option.

**Comment by Peter-Simpson** [comment]
Would the Action and SupportedActions methods help? 

⁣Sent from BlueMail ​

**Comment by dyfiastro** [comment]
I am not sure to be honest but its worth trying

**Comment by Peter-Simpson** [comment]
Closed because this isn't an issue with ASCOM Remote and no further update from dyfiastro.
