### ISSUE TITLE
ASCOM Remote Crash Loop 

### ISSUE THREAD

**Issue by tboneco** [ASCOMInitiative/ASCOMRemote#52]
I love using ASCOM Remote, but switched mounts recently.  When ASCOM Remote starts it tries to connect to my old mount.  If I click SETUP, it crashes.  I uninstalled and reinstalled ASCOM Remote but the old mount profile is still listed in the DEVICE CONFIGURATION page so ASCOM Remote keeps crashing when accessing SETUP even after reinstall.  Is there a way to completely delete ASCOM Remote or wipe out the DEVICE CONFIGURATION page so I can set up my new mount?  All other ASCOM pieces work great so I don't want to remove my entire ASCOM installation.

PS
I tripped over this problem 6 months ago and was able to figure out how to solve the issue but didn't write it down and now I cannot find online hints on how to do it.

**Comment by Peter-Simpson** [comment]
Hi,

The ASCOM Remote configuration is held in the user part of the registry in the key shown below, which you can delete using the Windows regedit tool or other registry editor:
 
`Computer\HKEY_CURRENT_USER\Software\ASCOM Remote `

If you make sure that ASCOM Remote is closed down, delete the registry key and restart ASCOM Remote, you will find that the it starts with its default "no configured devices" configuration.

Best wishes, Peter

**Comment by tboneco** [comment]
Thanks!
