### ISSUE TITLE
How to interface with the management API

### ISSUE THREAD

**Issue by zwik** [ASCOMInitiative/ASCOMRemote#9]
I just installed the latest version of ASCOMRemote and am able to interface with it. According to the documentation I should find a webinterface on /setup, or I should be able to get a list of available API on /management/apiversions. Both of them return a HTML page with "not found". I'm probably doing something wrong, but what? Can someone help me out?

Thanks!

**Comment by Peter-Simpson** [comment]
Hi Marcel,

 

We only finalised the management API recently and I haven’t had time to retrofit it to ASCOM Remote yet. I will put it on the request list, it certainly should be there!

 

Regards, Peter

**Comment by zwik** [comment]
Thanks Peter,

I just noticed in the settings that the management page is disabled. Is it an actual web page then or should I be able to configure/read everything from a JSON API? I would love a full JSON where configuration is only done with an API.

**Comment by Peter-Simpson** [comment]
Hi Marcel,

 

It’s deactivated because the current management API doesn’t comply with the standard, I’ll enable it again as soon as I’ve added the new capability.

 

Regards, Peter

**Comment by Peter-Simpson** [comment]
I'm closing this issue because the management interface and an HTML setup page have now been implemented in accordance with the Alpaca API. These will be released alongside the forthcoming Platform 6.5 release in the next one to two months.
